Make `stype` module private (#275)
### Description of this PR

Currently, mypy thinks `stype` is a module instead of a class, leading
to these errors. This PR fixes them by renaming the module `stype.py`
`_stype.py` to differentiate the class `stype` and the module `_stype`.
```diff
125d124
< torch_frame/datasets/fake.py:11: error: Name "stype" already defined (by an import)  [no-redef]
133,134d131
< torch_frame/datasets/fake.py:56: error: Module "torch_frame.stype" is not valid as a type  [valid-type]
< torch_frame/datasets/fake.py:56: note: Perhaps you meant to use a protocol matching the module structure?
138,140d134
< torch_frame/datasets/kdd_census_income.py:110: error: Module "torch_frame.stype" is not valid as a type  [valid-type]
< torch_frame/datasets/kdd_census_income.py:110: note: Perhaps you meant to use a protocol matching the module structure?
< torch_frame/datasets/kdd_census_income.py:11: error: Name "stype" already defined (by an import)  [no-redef]
286,290d279
< torch_frame/utils/infer_stype.py:140: error: Module "torch_frame.stype" is not valid as a type  [valid-type]
< torch_frame/utils/infer_stype.py:140: note: Perhaps you meant to use a protocol matching the module structure?
< torch_frame/utils/infer_stype.py:150: error: Need type annotation for "col_to_stype" (hint: "col_to_stype: Dict[<type>, <type>] = ...")  [var-annotated]
< torch_frame/utils/infer_stype.py:46: error: Module "torch_frame.stype" is not valid as a type  [valid-type]
< torch_frame/utils/infer_stype.py:46: note: Perhaps you meant to use a protocol matching the module structure?
```

### Breaking change

This is a breaking change for users importing `stype` as follows:
```python
from torch_frame.stype import stype
```
Instead, users should import the `stype` class via:
```python
from torch_frame import stype
```